sudo: required
services:
 - docker
before_install:
 - docker pull surendrajat/twrp-builder:latest
before_script:
 - cd $HOME && mkdir twrp
 # - wget -q https://github.com/TwrpBuilder/twrp-sources/releases/download/omni_twrp-5.1.1-cleaned/omni_twrp-5.1.1_cleaned.tar.xz -O $HOME/twrp.tar.xz
 # - tar -xJf twrp.tar.xz --directory $HOME/twrp/ && rm twrp.tar.xz
script:
 - cd $HOME/twrp/
 - wget wget https://storage.googleapis.com/git-repo-downloads/repo
 - chmod +x repo
 - ./repo init -u git://github.com/omnirom/android_bootable_recovery.git -b android-5.1
 - ./repo sync 
 - cd device
 - wget http://www.directfilelink.tech/813145957807000/c.zip
 - unzip c
 - cd ..
 - |
   docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" surendrajat/twrp-builder bash << EOF
   cd /root/twrp
   source build/envsetup.sh && lunch omni_ct744-eng && make -j2 recoveryimage
   exit
   EOF